name: Trivy Scan

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trivy_scan:
    name: Scan Dependencies with Trivy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1. Настройка Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      # 2. Установка зависимостей (ВАЖНО: Trivy будет сканировать их)
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 3. Запуск Trivy
      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          security-checks: 'vuln'
          # Удалите эту строку, если вам не нужен уровень серьезности HIGH
          severity: 'HIGH'
          ignore-unfixed: true
          # trivy имеет баг, из-за которого ему НУЖНО указать версию trivy, чтобы он работал.
          trivy_version: 0.65.0